
rx = rxsite("Name","Azurem", ...
 "Latitude",41.452997, ...
 "Longitude",-8.289737, ...
 "Antenna",design(dipole,tx.TransmitterFrequency), ...
 "AntennaHeight",25, ...
 "ReceiverSensitivity",-100); % Units: dBm 

tx = txsite("Name","Gualtar", ...
 "Latitude",41.560475, ...
 "Longitude",-8.399728, ...
 "Antenna",design(dipole,3e9), ...
 "AntennaHeight",25, ... % Units: meters
 "TransmitterFrequency",300e6, ... % Units: Hz
 "TransmitterPower",1);...pelo valor calculado em WaƩs.

viewer = siteviewer;
show(tx)
show(rx) 
coverage(tx,"freespace", "SignalStrengths",-100) 

coverage(tx,rx) 